Feature/advantages
SzymonSleboda/Project_Group_16 pull request #5
Opened 2022-12-16 16:14 UTC by WiktorSi

Tekst i tło zrobione. Pozostają do dodania PNG-i i wykonanie RWD.

2022-12-16 16:29 UTC, jaworskiwojciech requested changes
Widzę, że w Advantages masz <h1>. Może jednak warto zmienić na <h2> a dalsze na <h3>, bo jedynka raczej powinna być tylko raz, w moim odczuciu w tym hero-headerze.

2022-12-16 16:36 UTC, jaworskiwojciech reviewed
Widzę też w stylach advantages__title, że dałeś display:  none. Miał być ten tytuł komponentu jedynie widoczny dla robotów, ale nie jestem pewien, czy jak dasz display: none to cokolwiek go znajdzie. Ja bym chyba ten styl usunął. Wydaje mi się, że jak po prostu zostawisz go bez zawartości to nie będzie się pojawiał na stronie, ale będzie widoczny dla robotów.

2022-12-16 17:48 UTC, WiktorSi commented
Z H1 masz rację, do poprawki.
Co do tytułu, to właśnie nie jestem pewien, czy  jakiejś wartości nie powinien mieć.
Robot zobaczy tytuł, ale nie nauczy się czego dotyczy jak nie będzie wartości...

2022-12-16 21:09 UTC, jaworskiwojciech approved these changes
Zmieniono headingi. Bardzo dobrze!

2022-12-16 21:10 UTC, jaworskiwojciech approved these changes
Bardzo dobrze!

2022-12-16 21:11 UTC, jaworskiwojciech approved these changes
Dobrze!

2022-12-17 13:16 UTC, SzymonSleboda approved these changes
Super panowie. Przepycham, po spojrzeniu na całość sekcji będziemy patrzeć jeszcze potem, czy jest coś do zmiany.

2022-12-17 13:16 UTC, merged